"use client";

import { useMemo, useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { AppHeader } from "@/components/layout/app-header";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useMembers } from "@/hooks/use-members";
import { useMedicines } from "@/hooks/use-medicines";
import {
  Heart,
  Droplets,
  AlertTriangle,
  Phone,
  Pill,
  User,
  Share2,
  Download,
  Shield,
  QrCode,
} from "lucide-react";
import { toast } from "sonner";

function calculateAge(dateOfBirth: string): number | null {
  if (!dateOfBirth) return null;
  const birth = new Date(dateOfBirth);
  const today = new Date();
  let age = today.getFullYear() - birth.getFullYear();
  const monthDiff = today.getMonth() - birth.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birth.getDate())) {
    age--;
  }
  return age;
}

function formatGender(gender: string): string {
  if (!gender) return "Not specified";
  return gender.charAt(0).toUpperCase() + gender.slice(1);
}

export default function EmergencyCardPage() {
  const router = useRouter();
  const { members, isLoading: membersLoading } = useMembers();
  const [selectedMemberId, setSelectedMemberId] = useState<string>("");

  // Default to self member, or first member if no self exists
  useEffect(() => {
    if (selectedMemberId || members.length === 0) return;
    const self = members.find((m) => m.relation === "self");
    setSelectedMemberId(self?.id || members[0].id);
  }, [members, selectedMemberId]);

  const selfMember = useMemo(
    () => members.find((m) => m.id === selectedMemberId),
    [members, selectedMemberId]
  );

  const { activeMedicines, isLoading: medsLoading } = useMedicines(
    selfMember?.id
  );

  const age = selfMember?.date_of_birth
    ? calculateAge(selfMember.date_of_birth)
    : null;

  const handleShareCard = async () => {
    if (!selfMember) return;

    const lines: string[] = [
      "=== EMERGENCY HEALTH CARD ===",
      `Name: ${selfMember.name}`,
    ];

    if (selfMember.blood_group) {
      lines.push(`Blood Group: ${selfMember.blood_group}`);
    }
    if (selfMember.gender) {
      lines.push(`Gender: ${formatGender(selfMember.gender)}`);
    }
    if (age !== null) {
      lines.push(`Age: ${age} years`);
    }

    if (selfMember.allergies && selfMember.allergies.length > 0) {
      lines.push(`Allergies: ${selfMember.allergies.join(", ")}`);
    } else {
      lines.push("Allergies: None recorded");
    }

    if (selfMember.chronic_conditions && selfMember.chronic_conditions.length > 0) {
      lines.push(`Chronic Conditions: ${selfMember.chronic_conditions.join(", ")}`);
    } else {
      lines.push("Chronic Conditions: None recorded");
    }

    if (activeMedicines.length > 0) {
      const medList = activeMedicines
        .map((m) => `${m.name}${m.dosage ? ` (${m.dosage})` : ""}`)
        .join(", ");
      lines.push(`Current Medications: ${medList}`);
    } else {
      lines.push("Current Medications: None");
    }

    if (selfMember.emergency_contact_name || selfMember.emergency_contact_phone) {
      lines.push(
        `Emergency Contact: ${selfMember.emergency_contact_name || "N/A"} - ${selfMember.emergency_contact_phone || "N/A"}`
      );
    }

    if (selfMember.abha_number) {
      lines.push(`ABHA ID: ${selfMember.abha_number}`);
    }

    lines.push("", "Generated by MediFamily — https://medifamily.in");

    const text = lines.join("\n");

    try {
      if (navigator.share) {
        await navigator.share({
          title: `${selfMember.name} — Emergency Health Card`,
          text,
        });
      } else {
        await navigator.clipboard.writeText(text);
        toast.success("Emergency card copied to clipboard");
      }
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") return;
      toast.error("Failed to share");
    }
  };

  if (membersLoading || medsLoading) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </div>
    );
  }

  if (members.length === 0) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex flex-col items-center justify-center px-4 text-center">
          <div className="rounded-full bg-muted p-4 mb-4">
            <User className="h-8 w-8 text-muted-foreground" />
          </div>
          <h3 className="text-lg font-semibold mb-1">No Profile Found</h3>
          <p className="text-sm text-muted-foreground mb-4 max-w-xs">
            Add a family member to generate an emergency health card.
          </p>
          <Button onClick={() => router.push("/family/add")}>
            Add Member
          </Button>
        </div>
      </div>
    );
  }

  // Selector still resolving — show brief loading state
  if (!selfMember) {
    return (
      <div className="flex flex-col min-h-screen bg-background">
        <AppHeader title="Emergency Card" showBack />
        <div className="flex-1 flex items-center justify-center">
          <div className="animate-pulse text-muted-foreground">Loading...</div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <AppHeader title="Emergency Card" showBack />

      <main className="flex-1 px-4 py-4 pb-24 space-y-4 max-w-lg mx-auto w-full">
        {/* Member Selector — visible only if more than one member exists */}
        {members.length > 1 && (
          <div className="space-y-1">
            <p className="text-xs font-medium text-muted-foreground px-1">
              Select Family Member
            </p>
            <Select value={selectedMemberId} onValueChange={(v) => setSelectedMemberId(v || "")}>
              <SelectTrigger>
                <SelectValue placeholder="Select member" />
              </SelectTrigger>
              <SelectContent>
                {members.map((m) => (
                  <SelectItem key={m.id} value={m.id}>
                    {m.name} {m.relation === "self" ? "(You)" : `(${m.relation})`}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        )}

        {/* Emergency Card */}
        <Card className="overflow-hidden border-red-200 ring-red-200/50">
          {/* Red Header */}
          <div className="bg-red-600 px-4 py-3 flex items-center gap-2">
            <Heart className="h-5 w-5 text-white fill-white" />
            <span className="text-white font-bold text-sm tracking-wide uppercase">
              Emergency Health Card
            </span>
          </div>

          <CardContent className="pt-4 space-y-5">
            {/* Name */}
            <div>
              <p className="text-2xl font-bold text-foreground">
                {selfMember.name}
              </p>
            </div>

            {/* Vitals Row: Blood Group, Gender, Age */}
            <div className="grid grid-cols-3 gap-3">
              {/* Blood Group */}
              <div className="flex flex-col items-center rounded-lg border border-red-200 bg-red-50 dark:bg-red-950/20 p-3">
                <Droplets className="h-5 w-5 text-red-600 mb-1" />
                <span className="text-xs text-muted-foreground">Blood Group</span>
                <span className="text-xl font-bold text-red-600">
                  {selfMember.blood_group || "N/A"}
                </span>
              </div>

              {/* Gender */}
              <div className="flex flex-col items-center rounded-lg border bg-muted/30 p-3">
                <User className="h-5 w-5 text-muted-foreground mb-1" />
                <span className="text-xs text-muted-foreground">Gender</span>
                <span className="text-base font-semibold text-foreground">
                  {formatGender(selfMember.gender)}
                </span>
              </div>

              {/* Age */}
              <div className="flex flex-col items-center rounded-lg border bg-muted/30 p-3">
                <Shield className="h-5 w-5 text-muted-foreground mb-1" />
                <span className="text-xs text-muted-foreground">Age</span>
                <span className="text-xl font-bold text-foreground">
                  {age !== null ? age : "N/A"}
                </span>
              </div>
            </div>

            {/* Allergies */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <AlertTriangle className="h-4 w-4 text-red-600" />
                <h3 className="text-sm font-semibold text-foreground">
                  Allergies
                </h3>
              </div>
              {selfMember.allergies && selfMember.allergies.length > 0 ? (
                <div className="flex flex-wrap gap-1.5">
                  {selfMember.allergies.map((allergy, i) => (
                    <Badge
                      key={i}
                      className="bg-red-100 text-red-700 border-red-200 dark:bg-red-950/30 dark:text-red-400 dark:border-red-800"
                    >
                      {allergy}
                    </Badge>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">None recorded</p>
              )}
            </div>

            {/* Chronic Conditions */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <AlertTriangle className="h-4 w-4 text-orange-500" />
                <h3 className="text-sm font-semibold text-foreground">
                  Chronic Conditions
                </h3>
              </div>
              {selfMember.chronic_conditions &&
              selfMember.chronic_conditions.length > 0 ? (
                <div className="flex flex-wrap gap-1.5">
                  {selfMember.chronic_conditions.map((condition, i) => (
                    <Badge
                      key={i}
                      className="bg-orange-100 text-orange-700 border-orange-200 dark:bg-orange-950/30 dark:text-orange-400 dark:border-orange-800"
                    >
                      {condition}
                    </Badge>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">None recorded</p>
              )}
            </div>

            {/* Current Medications */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Pill className="h-4 w-4 text-blue-600" />
                <h3 className="text-sm font-semibold text-foreground">
                  Current Medications
                </h3>
              </div>
              {activeMedicines.length > 0 ? (
                <div className="space-y-1.5">
                  {activeMedicines.map((med) => (
                    <div
                      key={med.id}
                      className="flex items-center justify-between rounded-md bg-blue-50 dark:bg-blue-950/20 px-3 py-2 text-sm"
                    >
                      <span className="font-medium text-foreground">
                        {med.name}
                      </span>
                      {med.dosage && (
                        <span className="text-muted-foreground text-xs">
                          {med.dosage}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">None</p>
              )}
            </div>

            {/* Emergency Contact */}
            <div>
              <div className="flex items-center gap-2 mb-2">
                <Phone className="h-4 w-4 text-green-600" />
                <h3 className="text-sm font-semibold text-foreground">
                  Emergency Contact
                </h3>
              </div>
              {selfMember.emergency_contact_name ||
              selfMember.emergency_contact_phone ? (
                <div className="rounded-md bg-green-50 dark:bg-green-950/20 px-3 py-2">
                  {selfMember.emergency_contact_name && (
                    <p className="text-sm font-medium text-foreground">
                      {selfMember.emergency_contact_name}
                    </p>
                  )}
                  {selfMember.emergency_contact_phone && (
                    <a
                      href={`tel:${selfMember.emergency_contact_phone}`}
                      className="text-sm text-green-700 dark:text-green-400 font-semibold"
                    >
                      {selfMember.emergency_contact_phone}
                    </a>
                  )}
                </div>
              ) : (
                <p className="text-sm text-muted-foreground">Not set</p>
              )}
            </div>

            {/* ABHA ID */}
            {selfMember.abha_number && (
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Shield className="h-4 w-4 text-purple-600" />
                  <h3 className="text-sm font-semibold text-foreground">
                    ABHA ID
                  </h3>
                </div>
                <p className="text-sm font-mono text-foreground bg-purple-50 dark:bg-purple-950/20 px-3 py-2 rounded-md">
                  {selfMember.abha_number}
                  {selfMember.abha_address && (
                    <span className="block text-xs text-muted-foreground mt-0.5">
                      {selfMember.abha_address}
                    </span>
                  )}
                </p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Share Button */}
        <Button
          className="w-full bg-red-600 hover:bg-red-700 text-white"
          onClick={handleShareCard}
        >
          <Share2 className="h-4 w-4 mr-2" />
          Share Card
        </Button>

        {/* QR / Info Card */}
        <Card className="border-dashed border-red-200">
          <CardContent className="flex flex-col items-center text-center py-6 space-y-3">
            <div className="rounded-full bg-red-100 dark:bg-red-950/30 p-3">
              <QrCode className="h-8 w-8 text-red-600" />
            </div>
            <div>
              <p className="font-semibold text-foreground text-sm">
                Show this card to medical staff in emergencies
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                Keep your profile updated for accurate information
              </p>
            </div>
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground pt-1">
              <Heart className="h-3 w-3 text-red-500 fill-red-500" />
              <span className="font-medium">MediFamily</span>
              <span>- Your Family Health Manager</span>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  );
}
